name: Deploy to GitHub Pages

on:
  push:
    branches: [ production ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Debug secrets
      run: |
        echo "Checking if secrets are available..."
        if [ -n "${{ secrets.ADMIN_PASSWORD }}" ]; then
          echo "ADMIN_PASSWORD is set (length: ${#ADMIN_PASSWORD})"
        else
          echo "ADMIN_PASSWORD is NOT set"
        fi
        if [ -n "${{ secrets.API_ADMIN }}" ]; then
          echo "API_ADMIN is set (length: ${#API_ADMIN})"
        else
          echo "API_ADMIN is NOT set"
        fi
      
    - name: Create config.js with secrets
      run: |
        echo "window.ADMIN_CONFIG = {" > config.js
        echo "    password: '${{ secrets.ADMIN_PASSWORD || 'admin123' }}'," >> config.js
        echo "    githubToken: '${{ secrets.API_ADMIN }}'," >> config.js
        echo "    repository: '${{ github.repository }}'" >> config.js
        echo "};" >> config.js
        echo "Config.js created with repository: ${{ github.repository }}"
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 